### ISSUE TITLE
Command fuzzy filter

### ISSUE THREAD

**Issue by arkrost** [jonarrien/telescope-cmdline.nvim#14]
Hi! I stuck with the following problem. The `Git push --force` is not suggested on `pu force` input. It seems that prefix of each word should match exact, i.e. `pu -` works fine. How can I fix this?
<img width="1624" alt="Screenshot 2024-02-05 at 17 29 12" src="https://github.com/jonarrien/telescope-cmdline.nvim/assets/1239844/2dd2ad36-9a59-47c4-832b-9fe6e561c82d">

<img width="1624" alt="Screenshot 2024-02-05 at 17 24 03" src="https://github.com/jonarrien/telescope-cmdline.nvim/assets/1239844/6ff0ea49-8fca-434f-9bb0-4b1f998f2e12">

**Comment by sc0** [comment]
~~Hi! That'd be my doing – after typing space the list gets repopulated with both history entries and autocomplete and the fuzzy search results get lost. As @jonarrien noted in https://github.com/jonarrien/telescope-cmdline.nvim/pull/13, there is still place for improvement with fuzzy search. For now as a workaround I can only suggest skipping the space - `puforce` should work as expected.~~

Sorry, I looked at the code and I think the issue was in the different place. I'll file a PR that I believe will help.

**Comment by jonarrien** [comment]
Thanks for reporting @arkrost. I replicated the same issue with `:Git pull --rebase` and using `pure` without space made the trick. Thanks @sc0 for the suggestion. 

> I replaced fugitive with neogit and not typing git commands anymore, but I will check if there is any workaround for this edge case.

**Comment by jonarrien** [comment]
I've been refactoring a bit in PR #16. This scenario is working fine and I can filter `:Git pull --rebase` using `pure` (without `-` character). Please, give it a try.
