### ISSUE TITLE
<CR> should run input not history selection

### ISSUE THREAD

**Issue by PhilT** [jonarrien/telescope-cmdline.nvim#2]
So, it's not quite a replacement for `:` as you already mentioned.

If this is to be a replacement I think the default should be to run the input rather than the selection. Cmd history is normally opt-in so I think this makes sense and would align with `:`.

**Comment by jonarrien** [comment]
I keep it this way because normally I go up&down in history and press `<CR>` to run the command again.
If you want to adjust the command, press `<C-e>` to `edit` current selection. I think it's what you are looking for.

> NOTE: I did this intentionally to avoid some conflicts with autocompletion, but I'm pretty sure it can be improved.

**Comment by jonarrien** [comment]
I've been thinking thoroughly to use `<CR>` to run the input command, and even it's an easy change in mappings, I realised most of the times I want to use autocompletion results (99%).

I navigate the results (up & down) and press `<Tab>` key  to autocomplete it. For me pressing `<CR>` key more sense to select the result and it's also the normal behaviour for telescope plugins. In my daily workflow, I didn't find a case where I want to run something that doesn't appear in the list. 

However, you can use `<C-r> ` or `<C-CR>` to run the input rather than the selection.
